apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
    name: influxdb
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: rcp
  selector:
    app: influxdb

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influxdb
        - containerPort: 8088
          name: rcp
        livenessProbe:
          exec:
            command:
              - pgrep
              - influxd
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
          - mountPath: "/var/lib/influxdb"
            name: influxdb-pv-storage
      volumes:
        - name: influxdb-pv-storage
          persistentVolumeClaim:
            claimName: influxdb-pv-claim

