apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    app: wp
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
  selector:
    app: wp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      restartPolicy: Always
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
